### ISSUE TITLE
clone你的源码，编译时遇到这个问题，如何解决

### ISSUE THREAD

**Issue by mazige1997** [pexcn/padavan#1]
make[2]: Entering directory `/opt/rt-n56u/trunk/user/shadowsocks-libev'
( if [ -f ./config_done ]; then \
		echo "The same configuration."; \
	else \
		make configure && touch config_done; \
	fi )
make[3]: Entering directory `/opt/rt-n56u/trunk/user/shadowsocks-libev'
( cd shadowsocks-libev-2.5.5 ; \
	./configure \
		--disable-documentation \
		--disable-assert \
		--disable-ssp \
		--with-pcre=/opt/rt-n56u/trunk/user/shadowsocks-libev/prebuilts/pcre-8.39 \
		--with-openssl=/opt/rt-n56u/trunk/user/shadowsocks-libev/prebuilts/openssl-1.0.1 \
		--host=mipsel-linux \
		--build=x86_64-pc-linux-gnu ; \
	)
checking for mipsel-linux-gcc... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 accepts -g... yes
checking for /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 option to accept ISO C89... none needed
checking whether /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 understands -c and -o together... yes
checking how to run the C preprocessor... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mipsel-linux-strip... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2... gcc3
checking for mipsel-linux-ar... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ar
checking the archiver (/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... mipsel-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ld
checking if the linker (/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-nm
checking the name lister (/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to mipsel-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ld option to reload object files... -r
checking for mipsel-linux-objdump... no
checking for objdump... objdump
configure: WARNING: using cross tools not prefixed with host triplet
checking how to recognize dependent libraries... pass_all
checking for mipsel-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for mipsel-linux-ar... (cached) /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ar
checking for archiver @FILE support... @
checking for mipsel-linux-strip... (cached) /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-strip
checking for mipsel-linux-ranlib... /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ranlib
checking command to parse /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-nm output from /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 object... ok
checking for sysroot... no
checking for mipsel-linux-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 supports -fno-rtti -fno-exceptions... no
checking for /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 option to produce PIC... -fPIC -DPIC
checking if /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 PIC flag -fPIC -DPIC works... yes
checking if /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 static flag -static works... yes
checking if /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 supports -c -o file.o... yes
checking if /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 supports -c -o file.o... (cached) yes
checking whether the /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc -mips32r2 -march=mips32r2 linker (/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking checking for pcre includes in /opt/rt-n56u/trunk/user/shadowsocks-libev/prebuilts/pcre-8.39... checking for pcre headers in /opt/rt-n56u/trunk/user/shadowsocks-libev/prebuilts/pcre-8.39/include... not found
configure: adding /opt/rt-n56u/trunk/user/shadowsocks-libev/prebuilts/pcre-8.39/lib to RPATH
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
make[3]: *** [configure] Error 1
make[3]: Leaving directory `/opt/rt-n56u/trunk/user/shadowsocks-libev'
make[2]: *** [config_test] Error 2
make[2]: Leaving directory `/opt/rt-n56u/trunk/user/shadowsocks-libev'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/rt-n56u/trunk/user'
make: *** [user_only] Error 2

**Comment by pexcn** [comment]
缺少 `pcre` 库

**Comment by pexcn** [comment]
https://github.com/openwrt-dev/padavan/tree/master/trunk/user/shadowsocks-libev/prebuilts/pcre-8.39
https://github.com/openwrt-dev/padavan/blob/master/trunk/user/shadowsocks-libev/Makefile#L21-L22

**Comment by mazige1997** [comment]
Thanks very much

**Comment by pexcn** [comment]
Try last commit. @2812015651
