### ISSUE TITLE
我该如何安装pcre库

### ISSUE THREAD

**Issue by mazige1997** [pexcn/padavan#2]
按照百度的这个教程http://jingyan.baidu.com/article/7f766dafaed5e44100e1d041.html，./configure --prefix=/usr/local/pcre-8.37 --libdir=/usr/local/lib/pcre --includedir=/usr/local/include/pcre中prefix=/usr/local/pcre-8.37 --libdir=/usr/local/lib/pcre --includedir=/usr/local/include/pcre该如何配置，还是我找错了，求指点，替换为makefile中的路径也是跟之前的一样的错误

**Comment by pexcn** [comment]
你的系统是？如果是 Debian 系的就：`apt-get install libpcre3-dev`

**Comment by pexcn** [comment]
具体可以参考：https://github.com/shadowsocks/shadowsocks-libev#linux

**Comment by mazige1997** [comment]
还是一样的报错

**Comment by mazige1997** [comment]
ubuntu系统，sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev asciidoc xmlto，全部安装了

**Comment by pexcn** [comment]
那我就不清楚了。

**Comment by mazige1997** [comment]
问一下，不需要http://jingyan.baidu.com/article/7f766dafaed5e44100e1d041.html，./configure --prefix=/usr/local/pcre-8.37 --libdir=/usr/local/lib/pcre --includedir=/usr/local/include/pcre这样配置吧，只需安装apt-get install libpcre3-dev？

**Comment by pexcn** [comment]
不需要，而且我是这样改了之后就能编译成功了：https://github.com/openwrt-dev/padavan/commit/71e6204c1bbd6da1aba2298003b1b6fc51bbeb91 https://github.com/openwrt-dev/padavan/commit/5a411f394e7a893505f34d75ee01f515bd8a599a

**Comment by mazige1997** [comment]
额，我重装了系统，重新同步代码，重新安装所需软件包，还是一样的报错，只把.config中工具链改成/opt/rt-n56u.其余的同步下来的代码没改。你自己同步代码没问题吗，我按照wiki上的编译流程，ss需要的软件包我也全部安装了

**Comment by mazige1997** [comment]
你可以同步一下你的代码编译试试吗，我今天重复了好多次都是这个报错，我编译的系统是ubuntu14.04 32位 lts版

**Comment by pexcn** [comment]
难道不应该必须是64位系统吗？

**Comment by mazige1997** [comment]
我重新弄了一下，64位还是一样的报错，官方wiki的示例是ubuntu16.04 32位 lts

-

**Comment by pexcn** [comment]
那我就不清楚了

**Comment by mazige1997** [comment]
可以了，先要单独编译ss，我没有这么做

**Comment by mazige1997** [comment]
感谢

**Comment by pexcn** [comment]
我也没有，我之前是 clean 后直接编译就成功了。
